### ISSUE TITLE
GNOME 49 support

### ISSUE THREAD

**Issue by Boria138** [Vishram1123/gjs-osk#118]

**Comment by TheParadoxBox** [comment]
<img width="569" height="317" alt="Image" src="https://github.com/user-attachments/assets/ee4edefd-904b-4223-9a5f-7d50251af0c4" />

Doesn't work, unfortunately

**Comment by Vishram1123** [comment]
Could you check with the latest commit?

**Comment by Vishram1123** [comment]
Okay, so my latest release seems to work correctly in a gnome 49 vm, but clicking and dragging was a bit finicky (don't know if that was the vm's or keyboard's fault so I would appreciate if you all could confirm that it works).

**Comment by plumlis** [comment]
just tested.
Mostly works. But clouse button and dragging doesn't.

**Comment by Vishram1123** [comment]
Huh hold on

**Comment by Vishram1123** [comment]
I fixed it today; they replaced all of the click handling with the new Clutter.Gesture thing, so I had to clear all of the existing gestures associated with the button before adding my own. Also they got rid of their own EdgeDragAction and replace it another implementation, which works but it isn't as nice.

**Comment by TheParadoxBox** [comment]
Dragging is still finicky on my PC. Using autorelease 1be0132, everything works as expected until I click the drag bar; if you do that, it stays stuck to the mouse, and the only way to get it unstuck is to open the Activities view and click the panel indicator. There's some other weird behavior, but I have a feeling the cause is the same. As long as you don't click the drag bar, it works fine.

**Comment by Vishram1123** [comment]
> Dragging is still finicky on my PC. Using the version from the latest commit, everything works as expected until I click the drag bar; if you do that, it stays stuck to the mouse, and the only way to get it unstuck is to open the Activities view and click the panel indicator. There's some other weird behavior, but I have a feeling the cause is the same. As long as you don't click the drag bar, it works fine.

This is with the latest version?

**Comment by hgkamath** [comment]
> > Which autorelease is it (in Settings > About)?
> 
> It's autorelease [1be0132](https://github.com/Vishram1123/gjs-osk/commit/1be013235f60accedda3362a5dae7366f8f82381). The issue also occurs when I clone the latest commit, zip the source folder, and install it that way.
> 
> I can also confirm that the issue occurs using touch, but inconsistently. I also don't recall this ever happening before GNOME 49 was released.
> 
> EDIT: Just realized that there's a newer release, it just isn't marked as the latest or a pre-release. Trying it now.
> 
> EDIT 2: Bug still occurs using the very most recent autorelease (that isn't marked as the latest, but is actually newer).

- q1) which OS / linux distribution and version are you on?
- q2) are you using a VM ? if so which virtualization software - qemu/virtualbox? 
- q3) is OS latest with all drivers ? all patches updated  ? kernel version?
- q4) what is the hardware/brand/model of the mouse?

**Comment by TheParadoxBox** [comment]
1. Arch Linux, last updated today. fwupdmgr says all firmware is up to date.
2. No
3. Tested again today after updating, the issue persists. Kernel version is 6.16.8
4. Touchpad on a ThinkPad T14 Gen 5 AMD. I think it's manufactured by Synaptics. Also happens when using the touchscreen, but less consistently
5. No

**Comment by Vishram1123** [comment]
> > Which autorelease is it (in Settings > About)?
> 
> It's autorelease [1be0132](https://github.com/Vishram1123/gjs-osk/commit/1be013235f60accedda3362a5dae7366f8f82381). The issue also occurs when I clone the latest commit, zip the source folder, and install it that way.
> 
> I can also confirm that the issue occurs using touch, but inconsistently. I also don't recall this ever happening before GNOME 49 was released.
> 
> EDIT: Just realized that there's a newer release, it just isn't marked as the latest or a pre-release. Trying it now.
> 
> EDIT 2: Bug still occurs using the very most recent autorelease (that isn't marked as the latest, but is actually newer).

The latest autorelease is what Github marks as the latest; the Releases tab for some reason orders by seemingly arbitrary values, and it is not correct. 1be0132 is the latest release. I cannot reproduce this issue; if you could create a new issue and provide some extra logs, that would be greatly appreciated (log out/log in to Gnome, try dragging the keyboard, then run `journalctl --user` and provide the logs following the latest log stating that GNOME started)

**Comment by TheParadoxBox** [comment]
Sorry about the delay, here's the output of `journalctl --user -b` after restarting.

[journalctl.txt](https://github.com/user-attachments/files/22704895/journalctl.txt)

**Comment by Vishram1123** [comment]
> Sorry about the delay, here's the output of `journalctl --user -b` after restarting.
> 
> [journalctl.txt](https://github.com/user-attachments/files/22704895/journalctl.txt)

Oh, are you on X11? It isn't supported unfortunately

**Comment by TheParadoxBox** [comment]
I'm using Wayland, I think the X11-related messages are from XWayland. Regardless of that, though, if you search the log for "Wayland", you'll see that GNOME starts as a Wayland session.

**Comment by Vishram1123** [comment]
> I'm using Wayland, I think the X11-related messages are from XWayland. Regardless of that, though, if you search the log for "Wayland", you'll see that GNOME starts as a Wayland session.

I will look into this more when Fedora 43 releases. Please create a new issue in the meantime.

**Comment by hgkamath** [comment]
- This is something I just noticed. noting just for the record. It may be a transient that went away, but will keep watch if reliably reproducible 
- when a browser (firefox) tab that has a haptic input such as touchscreen/touchpad/mouse drawing app is open, and the user habit/need is to to alternative between touchscreen for drawing and touchpad for gui operation during phy-keyboard-typing 
  - the lower part of the screen behaved as if the osk was invisible but overlaid. 
  - mouse cursor would change on hover, raise the overlay osk, and uncecessarily cause a key to have pressed . the osk is then made to go clicking the x close-button 
  - the osk should show up, only if i use the touchscreen to touch into a GUI text field. but in this case I am using the touchpad to bring focus to the text-field. 
  - the bug went away on browser tab close+reopen.
    - maybe some bug in event system that relays a touchpad-press as a previously used touchscreen-press  
    - or maybe the gnome-shells automatic overlay raising an osk-on-top on touchsceen press has some role in it. 
  - unlike the SP3, on the HP-envy17t laptop I seldom use the touchscreen for typing as the phy-keyboard is at hand

**Comment by rexendevar** [comment]
Hi, on my system it says GJS OSK is for gnome 47??? How do i update it?

**Comment by rexendevar** [comment]
ok, turns out if you install an extension systemwide (which is required for it to function on the login page) then it will never auto update and there's no easy way to update it manually either. My install was sixteen full versions behind.

**Comment by Vishram1123** [comment]
I think the easiest way to do it is to clone the repo, then symlink the gjs-osk@vishram1123.com directory into the systemwide extensions folder. Then you can update using git pull
